spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect