apiVersion: apps/v1
kind: Deployment
metadata:
  name: asos-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asos-backend-app
  template:
    metadata:
      labels:
        app: asos-backend-app
    spec:
      containers:
      - image: andivx/asos-backend-app:main
        name: asos-backend-app
        imagePullPolicy: "Always"
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: config.json
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: url
---

apiVersion: v1
kind: Service
metadata:
  name: asos-backend-app
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "asos-backend-app"
    port: 8080
  selector:
    app: asos-backend-app
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type:
    NodePort
  ports:
    - port: 5432
  selector:
    app: postgres