name: Asos backend App

on:
  push:
    branches:
      - main
    paths:
      - 'asos-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle test
        run: cd asos-backend && ./gradlew test

  publish-backend-to-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build
        run: cd asos-backend && ./gradlew build

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: andivx/asos-backend-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./asos-backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy-backend-to-okteto:
    runs-on: ubuntu-latest
    needs: publish-backend-to-docker

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: okteto login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: okteto namespace
        uses: okteto/namespace@latest
        with:
          namespace: release-andi-mg

      - name: "Deploy application"
        uses: okteto/apply@latest
        with:
          manifest: ./asos-backend/k8s.yml