name: Asos backend App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'asos-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle test
        run: cd asos-backend && ./gradlew test

  publish-backend-to-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build
        run: cd asos-backend && ./gradlew build -x test

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: andivx/asos-backend-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./asos-backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  update-secrets-and-deploy-to-okteto:
    runs-on: ubuntu-latest
    needs: publish-backend-to-docker

    steps:
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: create db secrets
        uses: Azure/k8s-create-secret@v4
        with:
          namespace: andi-mg
          secret-type: 'generic'
          secret-name: datasource-credentials
          data: ${{ secrets.API_SECRET_DATA }}
      
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: okteto login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          namespace: andi-mg
          manifests: ./asos-backend/k8s.yml
          action: deploy
          strategy: basic

      - name: Restart instances
        run: kubectl rollout restart deployment asos-backend-app --namespace=andi-mg