name: Asos frontend

on:
  push:
    branches:
      - main
    paths:
      - 'asos-frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name:
        run: cd asos-frontend && yarn && yarn test